### ISSUE TITLE
README should specify "author_id" takes the id not email address

### ISSUE THREAD

**Issue by daguar** [phusion/frontapp#10]
Hi! Thanks for building this!

I just started using it, and wanted to flag that [in the README](https://github.com/phusion/frontapp/blob/master/README.md#comments) `author_id` is given as an email address, but it appears — through use — that the value should be the teammate ID from the Front API, rather than the email address of that teammate.

Thus the example of:

```ruby
comment = client.create_comment!("cnv_55c8c149", { author_id: "user@example.com", body: "text" })
```

should actually be something like

```ruby
comment = client.create_comment!("cnv_55c8c149", { author_id: "trd_rfjh", body: "text" })
```

I'm new to Front's API so opening this issue rather than immediately jumping to a PR in case there's a foible I'm not familiar with here.

Thanks again!

**Comment by scarhand** [comment]
Thanks for reporting this. I based the readme and its examples on [Front's api docs](https://dev.frontapp.com). They've probably updated the docs in the mean time.

It looks like the docs for this specific call, at https://dev.frontapp.com/#create-comment, now use a different format: `alt:email:leela@planet-express.com`
Would you be able to verify that that is also correct? In any case, you're more than welcome to submit a PR for this. The examples in the readme should resemble Front's examples as closely as possible.
