### ISSUE TITLE
Delete Contact Handle isn't working

### ISSUE THREAD

**Issue by bkubic** [phusion/frontapp#2]
Whenever I try to use the delete_contact_handle! method, I get an error saying the handle can't be found for the specified contact, even though the handle is clearly assigned to that contact.

**Comment by scarhand** [comment]
Sorry for the insanely late response. This project has not been on our radar for quite some time :(
Are you still experiencing this issue? I'm unfortunately not able to reproduce it. 

I've just tried it and `client.delete_contact_handle!(c_id, {handle: '@handle', source: 'twitter'})` returns `nil` and deletes the contact handle.

There is however a note in the [Front api docs](https://dev.frontapp.com/#delete-contact-handle):
> If the handle is the last handle of the contact, the API will return a 400 HTTP status code error.

Could that be the cause of the issue?
