### ISSUE TITLE
How to track errors?

### ISSUE THREAD

**Issue by IvRRimum** [phusion/frontapp#7]
Hey,

First off thanks for the library.

A question accoured, how can i track errors from the API? For example Unauhtorized error(so i can track whenever my token is correct/valid). I see it in object, but it's really not that accessable.

Thanks!

**Comment by scarhand** [comment]
There is a check in place to see if the response code returned by the Front api is success (2xx). If this is not the case an error is raised. For 400, 404 and 409 specific error classes are raised. There is indeed no specific error class for 401 Unauthorized responses. 
The response check was not done for `list` operations, such as `client.channels`. I have added the check there as well. I've also added a specific error class for 401's: UnauthorizedError.

You should now be able to do this:
```ruby
require 'frontapp'
client = Frontapp::Client.new(auth_token: 'token') 

begin
  channels = client.channels
rescue UnauthorizedError => e
  # oh no! unauthorized
rescue => e
  # something else didn't go as planned
end
```
